#!/bin/sh -e

# Remove symlink for el, replaced by a folder in 4.8.2-1
case "$1" in
install|upgrade)
    if dpkg --compare-versions "$2" lt "4.8.2-1"; then
      [ -h /usr/share/doc/xfce4-session/html/el/images ] && rm /usr/share/doc/xfce4-session/html/el/images || true
    fi
esac


# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/xfce4-tips-autostart.desktop 4.8.1-4 -- "$@"
# End automatically added section


exit 0
