#!/bin/sh

aspm="/sys/module/pcie_aspm/parameters/policy"

[ -w "$aspm" ] || exit $NA

case $1 in
    true) echo powersave > "$aspm";;
    false) echo default > "$aspm";;
    *) exit $NA;;
esac

exit 0